apiVersion: v1
kind: Service
metadata:
  name: anomaly-service
  labels:
    app.kubernetes.io/name: anomaly-service
spec:
  selector:
    app.kubernetes.io/name: anomaly-service
  ports:
    - name: http
      port: 8000
      targetPort: http
