apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: app
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    processors:
      batch: {}

    exporters:
      otlp/jaeger:
        endpoint: jaeger.observability.svc.cluster.local:4317
        tls:
          insecure: true
      debug:
        verbosity: basic

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, otlp/jaeger]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetrycollector
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetrycollector
  template:
    metadata:
      labels:
        app: opentelemetrycollector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.147.0
        args:
        - --config=/conf/config.yaml
        ports:
        - containerPort: 4317
        volumeMounts:
        - name: config
          mountPath: /conf
      volumes:
      - name: config
        configMap:
          name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetrycollector
  namespace: app
spec:
  selector:
    app: opentelemetrycollector
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
