apiVersion: v1
kind: Service
metadata:
  name: aiops-orchestrator
  labels:
    app.kubernetes.io/name: aiops-orchestrator
spec:
  selector:
    app.kubernetes.io/name: aiops-orchestrator
  ports:
    - name: http
      port: 8002
      targetPort: http
