apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-namespace.yaml
- ../../base
namespace: app
components:
- ../../components/jaeger-tracing
- ../../components/nodeport-frontend
