apiVersion: v1
kind: Service
metadata:
  name: rca-service
  labels:
    app.kubernetes.io/name: rca-service
spec:
  selector:
    app.kubernetes.io/name: rca-service
  ports:
    - name: http
      port: 8001
      targetPort: http
